flowchart TD

  A[1. Definição da intenção do produto]
  B[2. Design técnico de alto nível]
  C[3. Design técnico de baixo nível]
  D[4. Testes first]
  E[5. Implementação mínima passando nos testes] 
  F[6. Verificação e relatório de feedback]

  A-->B
  B-->C
  C-->D
  D-->E
  E-->F